### PR TITLE
add missing pluginlib in find packages

### PR DESCRIPTION
**Pull request by lianghongzhuo**
add missing pluginlib in find packages

### CODE REVIEW

**Comment by fmauch** [comment]
Thanks for pointing this out. It should also be added to the `CATKIN_DEPENDS` list.

**Comment by lianghongzhuo** [comment]
ok, done

**Review by fmauch — APPROVED** [review]
This is looking good to me! Thank you @lianghongzhuo

**Comment by fmauch** [comment]
and - as the CI correctly points out - in the package.xml

**Comment by lianghongzhuo** [comment]
could you run the ci again?

**Comment by lianghongzhuo** [comment]
fix ci again. this time I tested locally first.

**Pull request merged**
